### ISSUE TITLE
System hangs on stop

### ISSUE THREAD

**Issue by spoopers** [kodi-pvr/pvr.nextpvr#109]
I am having a strange issue on RPi4 running Libreelec, doesn't happen all the time, maybe once in ten times. When I press stop after watching Live TV for a while the system just hangs with a black screen, have left it over night and still just sits there with a black screen until I hard reboot. I don't get a crash log so system is not detecting a crash I guess. I have attached a log file from around the time it happened.

[kodi (1).log](https://github.com/kodi-pvr/pvr.nextpvr/files/4080303/kodi.1.log)

**Comment by emveepee** [comment]
Several users have reported intermittent issues with the timeshifting code but the author of the code has not responded to any of these reports on the Kodi or NextPVR forums and I don't expect a solution. The best solution when 3.3.18 is available on LE is to upgrade to NextPVR v5 which provides much more stable timeshifting .  Until then Extended Timeshift and Real Time modes in V4 are more reliable.   Support questions should be posted on the appropriate forum.

**Comment by spoopers** [comment]
Still happening with NPVR V5 and Kodi plugin 3.3.18.

**Comment by emveepee** [comment]
The rules of Kodi issue reporting https://github.com/xbmc/xbmc/issues/new?template=bug_report.md are pretty clear that you need to include the complete debug log or this will be marked closed

**Comment by spoopers** [comment]
## Bug report
### Describe the bug
Here is a clear and concise description of what the problem is: 



When stopping live TV with NextPVR addon the system goes to a black screen and Kodi becomes unresponsive. 
Hotkey set up to restart Kodi does not work when the screen goes black and have to use another hotkey that calls a system script to restart the device.
This is on Librelec 9.2 on a Raspberry Pi 4, NextPVR addon 3.3.18.1, NextPVR v5, behaviour was the same with NextPVR v4. This happens with both Live TV and Recordings. Seems to happen more with DVB-T HD channels but also with DVB-S HD channels too at times.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:


Press stop and system should return to TV Guide or Recording list.


## Actual Behavior


Press stop and black screen with system unresponsive.


## Possible Fix





### To Reproduce
Steps to reproduce the behavior:



1. Play DVB-T HD channel for extended period.
2. Press stop.
3. Black screen.


### Debuglog


The debuglog can be found here:
[https://forum.libreelec.tv/thread/20795-system-hangs-on-live-tv-stop/](url)


### Screenshots 
Here are some links or screenshots to help explain the problem:




## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:


Happens everyday, several times per day.


### Your Environment
Used Operating system:


 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
18.5



*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by emveepee** [comment]
That log was just your old snippet which I said I wouldn't investigate and applies to 18.5 with an unknown addon version.   

Please include the complete debug log using v5 and the newer 3.3.18

**Comment by spoopers** [comment]
That might take a few days, I will see what I can do.

**Comment by emveepee** [comment]
I followed your link to the LE forums you probably should just have posted on the NextPVR forum to avoid the formality on github.   Hopefully you now use advancedsettings to enable debug logging without disturbing your wife.

**Comment by spoopers** [comment]
Ok just got it to happen there now, log files are pretty big, 61MB at time of crash and 34MB after reboot, can I send a sharing link?

**Comment by emveepee** [comment]
If you are ok with posting a public link here sure, but zip them first and save the zip because you may get referred back to LE forums

**Comment by spoopers** [comment]
[https://drive.google.com/open?id=1Jkflh8N9omVULAXiPdCyuuVmsZeGjoPI](url) - At time of black screen.
[https://drive.google.com/open?id=1rgtWgO3VsN9Cywjfp2RSy-iqanG2RArO](url) - After reboot post black screen.

Will leave them here for a bit and delete later, God knows what is in them.

**Comment by emveepee** [comment]
Playback stopped fine 
2020-03-16 17:32:24.620 T:2165302128   DEBUG: AddOnLog: NextPVR PVR Client: CloseLiveStream@exit

and the addon continued working and shutdown so it didn't seem to crash since it was shutdown

2020-03-16 17:32:56.916 T:3011383904  NOTICE: PVR Manager: Stopped
2020-03-16 17:32:56.933 T:3011383904   DEBUG: Destroy: Destroying PVR add-on instance 'NextPVR  (192.168.0.90):connected'
2020-03-16 17:32:57.320 T:3011383904   DEBUG: AddOnLog: NextPVR PVR Client: ->~cPVRClientNextPVR()
2020-03-16 17:32:57.321 T:3011383904   DEBUG: SECTION:UnloadDll(/storage/.kodi/addons/pvr.nextpvr/pvr.nextpvr.so.3.3.18)
2020-03-16 17:32:57.321 T:3011383904    INFO: ADDON: Dll Destroyed - NextPVR PVR Client

I would have the LE people look at the log and start here

2020-03-16 17:32:52.471 T:2932626288   DEBUG: LIRC: - NEW 160 0 KEY_OK devinput (KEY_OK)
2020-03-16 17:32:52.527 T:3011383904   DEBUG: HandleKey: 11 (0x0b, obc244) pressed, action is Select
2020-03-16 17:32:52.610 T:3011383904    INFO: Saving exitCode 66
2020-03-16 17:32:52.666 T:3011383904   DEBUG: ------ Window Init (DialogBusy.xml) ------
2020-03-16 17:32:52.737 T:3011383904   DEBUG: Alignment of external buffer is not suitable for ffmpeg intrinsics - please fix your malloc
2020-03-16 17:32:52.991 T:3011383904   DEBUG: Previous line repeats 1 times.
2020-03-16 17:32:52.991 T:3011383904   DEBUG: Error [-541478725] while reading frame: Unknown error 541478725
2020-03-16 17:32:53.027 T:3011383904  NOTICE: Quitting due to POSIX signal

**Comment by spoopers** [comment]
Thanks will do, much appreciated.

**Comment by spoopers** [comment]
Have taken the above log files down for now, if anyone would like a copy please send me a message and I will provide a link.
